site_name: "ML Notes â€” pushkarnagar"
site_url: https://pushkarnagar.github.io
nav:
  - Home: index.md
  - Basics:
      - Linear Regression: 00-basics/linear_regression.md
theme:
  name: material
plugins:
  - search
  - mkdocs-jupyter
markdown_extensions:
  - pymdownx.superfences
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/math-render.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pushkarnagar/pushkarnagar.github.io
